# Laboratory Work 4 - NumPy Library Basics
**Variant 12**

**Student:** Dmytro Zamaraiev

### Exercise 2: Checkerboard Pattern

**Task:** Enter the number n. Arrange 1 and 0 in a checkerboard pattern, starting with 0 in a matrix of size n×n, using slicing.

In [45]:
import numpy as np
import time

def exercise_2_numpy(n):
    matrix = np.zeros((n, n), dtype=int)
    matrix[::2, 1::2] = 1
    matrix[1::2, ::2] = 1
    return matrix

def exercise_2_iterative(n):
    matrix = [[0 for _ in range(n)] for _ in range(n)]
    for i in range(n):
        for j in range(n):
            if (i + j) % 2 == 1:
                matrix[i][j] = 1
    return np.array(matrix)

n = int(input("Enter n: "))

start = time.time()
result_numpy = exercise_2_numpy(n)
time_numpy = time.time() - start

start = time.time()
result_iter = exercise_2_iterative(n)
time_iter = time.time() - start

print("NumPy result:")
print(result_numpy)
print(f"\nNumPy time: {time_numpy:.6f}s")
print(f"Iterative time: {time_iter:.6f}s")
print(f"Speedup: {time_iter/time_numpy:.1f}x")
print(f"\nResults match: {np.allclose(result_numpy, result_iter)}")

Enter n:  8


NumPy result:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]

NumPy time: 0.000123s
Iterative time: 0.000113s
Speedup: 0.9x

Results match: True


### Exercise 3: Selective Row and Column Zeros

**Task:** Enter 4 numbers n, m, r, c. Output an array of size n×m, in which in each r-th row and in each c-th column are 0, and other elements are equal to 1.

In [48]:
import numpy as np
import time

def exercise_3_numpy(n, m, r, c):
    matrix = np.ones((n, m), dtype=int)
    matrix[::r, :] = 0
    matrix[:, ::c] = 0
    return matrix

def exercise_3_iterative(n, m, r, c):
    matrix = [[1 for _ in range(m)] for _ in range(n)]
    for i in range(n):
        for j in range(m):
            if i % r == 0 or j % c == 0:
                matrix[i][j] = 0
    return np.array(matrix)

n = int(input("Enter n: "))
m = int(input("Enter m: "))
r = int(input("Enter r: "))
c = int(input("Enter c: "))

start = time.time()
result_numpy = exercise_3_numpy(n, m, r, c)
time_numpy = time.time() - start

start = time.time()
result_iter = exercise_3_iterative(n, m, r, c)
time_iter = time.time() - start

print("NumPy result:")
print(result_numpy)
print(f"\nNumPy time: {time_numpy:.6f}s")
print(f"Iterative time: {time_iter:.6f}s")
print(f"Speedup: {time_iter/time_numpy:.1f}x")
print(f"\nResults match: {np.allclose(result_numpy, result_iter)}")

Enter n:  6
Enter m:  7
Enter r:  2
Enter c:  3


NumPy result:
[[0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]]

NumPy time: 0.005513s
Iterative time: 0.000179s
Speedup: 0.0x

Results match: True


### Exercise 5: Even Row Indices Pattern

**Task:** Enter the number n. Output an array of size n×n, in which the rows with the even indices are equal to 1, and in others are equal to 0.

In [51]:
import numpy as np
import time

def exercise_5_numpy(n):
    matrix = np.zeros((n, n), dtype=int)
    matrix[::2, :] = 1
    return matrix

def exercise_5_iterative(n):
    matrix = [[0 for _ in range(n)] for _ in range(n)]
    for i in range(n):
        if i % 2 == 0:
            for j in range(n):
                matrix[i][j] = 1
    return np.array(matrix)

n = int(input("Enter n: "))

start = time.time()
result_numpy = exercise_5_numpy(n)
time_numpy = time.time() - start

start = time.time()
result_iter = exercise_5_iterative(n)
time_iter = time.time() - start

print("NumPy result:")
print(result_numpy)
print(f"\nNumPy time: {time_numpy:.6f}s")
print(f"Iterative time: {time_iter:.6f}s")
print(f"Speedup: {time_iter/time_numpy:.1f}x")
print(f"\nResults match: {np.allclose(result_numpy, result_iter)}")

Enter n:  5


NumPy result:
[[1 1 1 1 1]
 [0 0 0 0 0]
 [1 1 1 1 1]
 [0 0 0 0 0]
 [1 1 1 1 1]]

NumPy time: 0.005534s
Iterative time: 0.000348s
Speedup: 0.1x

Results match: True


### Exercise 14: Checkerboard Using numpy.tile()

**Task:** Arrange 1 and 0 on the 8×8 field in a checkerboard pattern using the numpy tile().

In [52]:
import numpy as np
import time

def exercise_14_numpy():
    base = np.array([[0, 1], [1, 0]])
    return np.tile(base, (4, 4))

def exercise_14_iterative():
    matrix = [[0 for _ in range(8)] for _ in range(8)]
    for i in range(8):
        for j in range(8):
            if (i + j) % 2 == 1:
                matrix[i][j] = 1
    return np.array(matrix)

start = time.time()
result_numpy = exercise_14_numpy()
time_numpy = time.time() - start

start = time.time()
result_iter = exercise_14_iterative()
time_iter = time.time() - start

print("NumPy result:")
print(result_numpy)
print(f"\nNumPy time: {time_numpy:.6f}s")
print(f"Iterative time: {time_iter:.6f}s")
print(f"Speedup: {time_iter/time_numpy:.1f}x")
print(f"\nResults match: {np.allclose(result_numpy, result_iter)}")

NumPy result:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]

NumPy time: 0.002280s
Iterative time: 0.000120s
Speedup: 0.1x

Results match: True


### Exercise 17: Sign Reversal Based on Range

**Task:** Fill the vector with values from 0 to n. Replace signs for all values less than n/2 and greater than 3n/4 to opposite ones.

In [53]:
import numpy as np
import time

def exercise_17_numpy(n):
    vector = np.arange(n + 1)
    mask = (vector < n/2) | (vector > 3*n/4)
    vector[mask] = -vector[mask]
    return vector

def exercise_17_iterative(n):
    vector = list(range(n + 1))
    for i in range(len(vector)):
        if vector[i] < n/2 or vector[i] > 3*n/4:
            vector[i] = -vector[i]
    return np.array(vector)

n = int(input("Enter n: "))

start = time.time()
result_numpy = exercise_17_numpy(n)
time_numpy = time.time() - start

start = time.time()
result_iter = exercise_17_iterative(n)
time_iter = time.time() - start

print("NumPy result:")
print(result_numpy)
print(f"\nNumPy time: {time_numpy:.6f}s")
print(f"Iterative time: {time_iter:.6f}s")
print(f"Speedup: {time_iter/time_numpy:.1f}x")
print(f"\nResults match: {np.allclose(result_numpy, result_iter)}")

Enter n:  10


NumPy result:
[  0  -1  -2  -3  -4   5   6   7  -8  -9 -10]

NumPy time: 0.002424s
Iterative time: 0.000209s
Speedup: 0.1x

Results match: True


### Exercise 18: Unique Elements Count

**Task:** Generate a vector of n random numbers in the range from 0 to 99. Determine the number of unique elements in the sequence.

In [54]:
import numpy as np
import time

def exercise_18_numpy(n):
    vector = np.random.randint(0, 100, n)
    unique_count = len(np.unique(vector))
    return vector, unique_count

def exercise_18_iterative(vector):
    unique_set = set()
    for val in vector:
        unique_set.add(val)
    return len(unique_set)

n = int(input("Enter n: "))

start = time.time()
vector, count_numpy = exercise_18_numpy(n)
time_numpy = time.time() - start

start = time.time()
count_iter = exercise_18_iterative(vector)
time_iter = time.time() - start

print(f"Vector: {vector}")
print(f"\nUnique elements (NumPy): {count_numpy}")
print(f"Unique elements (Iterative): {count_iter}")
print(f"\nNumPy time: {time_numpy:.6f}s")
print(f"Iterative time: {time_iter:.6f}s")
print(f"Speedup: {time_iter/time_numpy:.1f}x")
print(f"\nResults match: {count_numpy == count_iter}")

Enter n:  30


Vector: [ 1 87 29 37  1 63 59 20 32 75 57 21 88 48 90 58 41 91 59 79 14 61 61 46
 61 50 54 63  2 50]

Unique elements (NumPy): 24
Unique elements (Iterative): 24

NumPy time: 0.008684s
Iterative time: 0.000182s
Speedup: 0.0x

Results match: True


### Exercise 19: Evenly Spaced Values on Open Interval

**Task:** Generate a vector of n elements that are evenly spaced on the interval (0,1) i.e. both ends of the interval are not included. Output values up to 3 decimal places.

**Mathematical representation:**
For $n$ points on open interval $(0, 1)$:
$$
x_i = \frac{i+1}{n+1}, \quad i = 0, 1, 2, \ldots, n-1
$$

In [55]:
import numpy as np
import time

def exercise_19_numpy(n):
    vector = np.linspace(0, 1, n + 2)[1:-1]
    return np.round(vector, 3)

def exercise_19_iterative(n):
    vector = [(i + 1) / (n + 1) for i in range(n)]
    return np.round(vector, 3)

n = int(input("Enter n: "))

start = time.time()
result_numpy = exercise_19_numpy(n)
time_numpy = time.time() - start

start = time.time()
result_iter = exercise_19_iterative(n)
time_iter = time.time() - start

print("NumPy result:")
print(result_numpy)
print(f"\nNumPy time: {time_numpy:.6f}s")
print(f"Iterative time: {time_iter:.6f}s")
print(f"Speedup: {time_iter/time_numpy:.1f}x")
print(f"\nResults match: {np.allclose(result_numpy, result_iter)}")

Enter n:  10


NumPy result:
[0.091 0.182 0.273 0.364 0.455 0.545 0.636 0.727 0.818 0.909]

NumPy time: 0.002153s
Iterative time: 0.000198s
Speedup: 0.1x

Results match: True


### Exercise 20: Replace Maximum with Zero

**Task:** Generate a vector of n random elements, lying in the interval (0,1). Replace the maximum element with 0.

In [56]:
import numpy as np
import time

def exercise_20_numpy(n):
    vector = np.random.rand(n)
    initial = vector.copy()
    max_idx = np.argmax(vector)
    vector[max_idx] = 0
    return initial, vector

def exercise_20_iterative(n):
    vector = np.random.rand(n)
    initial = vector.copy()
    max_idx = 0
    for i in range(1, n):
        if vector[i] > vector[max_idx]:
            max_idx = i
    vector[max_idx] = 0
    return initial, vector

n = int(input("Enter n: "))

start = time.time()
initial_numpy, result_numpy = exercise_20_numpy(n)
time_numpy = time.time() - start

start = time.time()
initial_iter, result_iter = exercise_20_iterative(n)
time_iter = time.time() - start

print("Initial vector:")
print(np.round(initial_numpy, 3))
print("\nModified vector:")
print(np.round(result_numpy, 3))
print(f"\nNumPy time: {time_numpy:.6f}s")
print(f"Iterative time: {time_iter:.6f}s")
print(f"Speedup: {time_iter/time_numpy:.1f}x")
print(f"\nResults match: {np.allclose(result_numpy, result_iter)}")

Enter n:  5


Initial vector:
[0.68  0.45  0.013 0.942 0.563]

Modified vector:
[0.68  0.45  0.013 0.    0.563]

NumPy time: 0.003278s
Iterative time: 0.000159s
Speedup: 0.0x

Results match: False


### Exercise 21: Negate All Maximum Elements

**Task:** Enter the numbers n and m. Generate a matrix n×n of random integer elements from 0 to m. Change the signs of all maximum elements to the opposite.

In [57]:
import numpy as np
import time

def exercise_21_numpy(n, m):
    matrix = np.random.randint(0, m, (n, n))
    initial = matrix.copy()
    max_val = np.max(matrix)
    matrix[matrix == max_val] = -max_val
    return initial, matrix

def exercise_21_iterative(n, m):
    matrix = np.random.randint(0, m, (n, n))
    initial = matrix.copy()
    max_val = matrix[0][0]
    for i in range(n):
        for j in range(n):
            if matrix[i][j] > max_val:
                max_val = matrix[i][j]
    for i in range(n):
        for j in range(n):
            if matrix[i][j] == max_val:
                matrix[i][j] = -max_val
    return initial, matrix

n = int(input("Enter n: "))
m = int(input("Enter m: "))

start = time.time()
initial_numpy, result_numpy = exercise_21_numpy(n, m)
time_numpy = time.time() - start

start = time.time()
initial_iter, result_iter = exercise_21_iterative(n, m)
time_iter = time.time() - start

print("Initial matrix:")
print(initial_numpy)
print("\nModified matrix:")
print(result_numpy)
print(f"\nNumPy time: {time_numpy:.6f}s")
print(f"Iterative time: {time_iter:.6f}s")
print(f"Speedup: {time_iter/time_numpy:.1f}x")
print(f"\nResults match: {np.allclose(result_numpy, result_iter)}")

Enter n:  4
Enter m:  10


Initial matrix:
[[7 2 0 3]
 [1 7 3 1]
 [5 5 9 3]
 [5 1 9 1]]

Modified matrix:
[[ 7  2  0  3]
 [ 1  7  3  1]
 [ 5  5 -9  3]
 [ 5  1 -9  1]]

NumPy time: 0.008460s
Iterative time: 0.000654s
Speedup: 0.1x

Results match: False


## PART 2: Linear Equation System

**Task:** Solve the following system of linear equations:

$$
\begin{cases}
x_1 + x_2 - x_3 - x_4 = 0 \\
x_2 + 2x_3 - x_4 = 2 \\
x_1 - x_2 - x_4 = -1 \\
-x_1 + 3x_2 - 2x_3 = 0
\end{cases}
$$

**Methods:**
1. Cramer's Rule
2. Inverse Matrix Method
3. numpy.linalg.solve()

In [32]:
import numpy as np
import time

A = np.array([
    [1,  1, -1, -1],
    [0,  1,  2, -1],
    [1, -1,  0, -1],
    [-1, 3, -2,  0]
], dtype=float)

b = np.array([0, 2, -1, 0], dtype=float)

print("Coefficient matrix A:")
print(A)
print("\nRight-hand side vector b:")
print(b)

Coefficient matrix A:
[[ 1.  1. -1. -1.]
 [ 0.  1.  2. -1.]
 [ 1. -1.  0. -1.]
 [-1.  3. -2.  0.]]

Right-hand side vector b:
[ 0.  2. -1.  0.]


### Method 1: Cramer's Rule

In [33]:
import numpy as np
import time

def cramers_rule(A, b):
    n = len(b)
    det_A = np.linalg.det(A)
    x = np.zeros(n)
    for i in range(n):
        A_i = A.copy()
        A_i[:, i] = b
        x[i] = np.linalg.det(A_i) / det_A
    return x

print("="*40)
print("METHOD 1: CRAMER'S RULE")
print("="*40)

x_cramer = cramers_rule(A, b)

print(f"\nDeterminant of A: {np.linalg.det(A):.6f}")
print("\nSolution:")
for i, val in enumerate(x_cramer, 1):
    print(f"x{i} = {val:.6f}")

METHOD 1: CRAMER'S RULE

Determinant of A: -7.000000

Solution:
x1 = 1.000000
x2 = 1.000000
x3 = 1.000000
x4 = 1.000000


### Verification 1: Matrix Multiplication

In [34]:
import numpy as np
import time

print("\n" + "="*40)
print("VERIFICATION 1: MATRIX MULTIPLICATION")
print("="*40)

b_check = A @ x_cramer

print("\nComputing Ax:")
print(f"A @ x = {b_check}")
print(f"b     = {b}")
print(f"\nMatch: {np.allclose(b_check, b)}")


VERIFICATION 1: MATRIX MULTIPLICATION

Computing Ax:
A @ x = [-0.  2. -1. -0.]
b     = [ 0.  2. -1.  0.]

Match: True


### Method 2: Inverse Matrix

In [35]:
import numpy as np
import time

print("\n" + "="*40)
print("METHOD 2: INVERSE MATRIX")
print("="*40)

A_inv = np.linalg.inv(A)
x_inv = A_inv @ b

print("\nInverse matrix A^(-1):")
print(A_inv)
print("\nSolution:")
for i, val in enumerate(x_inv, 1):
    print(f"x{i} = {val:.6f}")


METHOD 2: INVERSE MATRIX

Inverse matrix A^(-1):
[[ 1.428571 -0.142857 -1.285714 -0.857143]
 [ 0.571429  0.142857 -0.714286 -0.142857]
 [ 0.142857  0.285714 -0.428571 -0.285714]
 [ 0.857143 -0.285714 -1.571429 -0.714286]]

Solution:
x1 = 1.000000
x2 = 1.000000
x3 = 1.000000
x4 = 1.000000


### Verification 2: Inverse Matrix Check

In [36]:
import numpy as np
import time

print("\n" + "="*40)
print("VERIFICATION 2: INVERSE MATRIX METHOD")
print("="*40)

b_check = A @ x_inv

print("\nComputing Ax:")
print(f"A @ x = {b_check}")
print(f"b     = {b}")
print(f"\nMatch: {np.allclose(b_check, b)}")


VERIFICATION 2: INVERSE MATRIX METHOD

Computing Ax:
A @ x = [ 0.  2. -1.  0.]
b     = [ 0.  2. -1.  0.]

Match: True


### Method 3: numpy.linalg.solve()

In [37]:
import numpy as np
import time

print("\n" + "="*40)
print("METHOD 3: numpy.linalg.solve()")
print("="*40)

x_solve = np.linalg.solve(A, b)

print("\nSolution:")
for i, val in enumerate(x_solve, 1):
    print(f"x{i} = {val:.6f}")


METHOD 3: numpy.linalg.solve()

Solution:
x1 = 1.000000
x2 = 1.000000
x3 = 1.000000
x4 = 1.000000


### Verification 3: np.linalg.solve() Check

In [38]:
import numpy as np
import time

print("\n" + "="*40)
print("VERIFICATION 3: numpy.linalg.solve()")
print("="*40)

b_check = A @ x_solve

print("\nComputing Ax:")
print(f"A @ x = {b_check}")
print(f"b     = {b}")
print(f"\nMatch: {np.allclose(b_check, b)}")


VERIFICATION 3: numpy.linalg.solve()

Computing Ax:
A @ x = [ 0.  2. -1.  0.]
b     = [ 0.  2. -1.  0.]

Match: True


### Comparison of All Methods

In [39]:
import numpy as np
import time
import pandas as pd

print("\n" + "="*40)
print("COMPARISON OF ALL METHODS")
print("="*40)

print("\nAll methods produce the same result:")
print(f"Cramer vs Inverse: {np.allclose(x_cramer, x_inv)}")
print(f"Cramer vs Solve: {np.allclose(x_cramer, x_solve)}")
print(f"Inverse vs Solve: {np.allclose(x_inv, x_solve)}")

df = pd.DataFrame({
    'Variable': [f'x{i}' for i in range(1, 5)],
    'Cramer': x_cramer,
    'Inverse': x_inv,
    'np.solve': x_solve
})

print("\nSolution comparison:")
print(df.to_string(index=False))


COMPARISON OF ALL METHODS

All methods produce the same result:
Cramer vs Inverse: True
Cramer vs Solve: True
Inverse vs Solve: True

Solution comparison:
Variable  Cramer  Inverse  np.solve
      x1     1.0      1.0       1.0
      x2     1.0      1.0       1.0
      x3     1.0      1.0       1.0
      x4     1.0      1.0       1.0


## PART 3: Matrix Expression Evaluation

**Task:** Calculate the value of the matrix expression:

$$
A(A^2 - B) - 2(B + A)B
$$

where:

$$
A = \begin{pmatrix}
2 & 3 & 1 \\
-1 & 2 & 4 \\
5 & 3 & 0
\end{pmatrix}, \quad
B = \begin{pmatrix}
2 & 7 & 13 \\
-1 & 0 & 5 \\
5 & 13 & 21
\end{pmatrix}
$$

In [40]:
import numpy as np
import time

A = np.array([
    [2,  3, 1],
    [-1, 2, 4],
    [5,  3, 0]
], dtype=float)

B = np.array([
    [2,  7, 13],
    [-1, 0,  5],
    [5, 13, 21]
], dtype=float)

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)

Matrix A:
[[ 2.  3.  1.]
 [-1.  2.  4.]
 [ 5.  3.  0.]]

Matrix B:
[[ 2.  7. 13.]
 [-1.  0.  5.]
 [ 5. 13. 21.]]


### NumPy Implementation

In [41]:
import numpy as np
import time

def matrix_expression_numpy(A, B):
    A2 = A @ A
    term1 = A @ (A2 - B)
    term2 = 2 * (B + A) @ B
    result = term1 - term2
    return result

print("="*40)
print("NUMPY IMPLEMENTATION")
print("="*40)

start = time.time()
result_numpy = matrix_expression_numpy(A, B)
time_numpy = time.time() - start

print("\nResult:")
print(result_numpy)
print(f"\nTime: {time_numpy:.6f}s")

NUMPY IMPLEMENTATION

Result:
[[  -75.  -357.  -788.]
 [  -40.  -156.  -359.]
 [ -147.  -607. -1291.]]

Time: 0.003694s


### Iterative Implementation

In [42]:
import numpy as np
import time

def matrix_multiply(X, Y):
    n, m = len(X), len(X[0])
    m2, p = len(Y), len(Y[0])
    result = [[0 for _ in range(p)] for _ in range(n)]
    for i in range(n):
        for j in range(p):
            for k in range(m):
                result[i][j] += X[i][k] * Y[k][j]
    return result

def matrix_add(X, Y):
    n, m = len(X), len(X[0])
    result = [[0 for _ in range(m)] for _ in range(n)]
    for i in range(n):
        for j in range(m):
            result[i][j] = X[i][j] + Y[i][j]
    return result

def matrix_subtract(X, Y):
    n, m = len(X), len(X[0])
    result = [[0 for _ in range(m)] for _ in range(n)]
    for i in range(n):
        for j in range(m):
            result[i][j] = X[i][j] - Y[i][j]
    return result

def scalar_multiply(scalar, X):
    n, m = len(X), len(X[0])
    result = [[0 for _ in range(m)] for _ in range(n)]
    for i in range(n):
        for j in range(m):
            result[i][j] = scalar * X[i][j]
    return result

def matrix_expression_iterative(A, B):
    A_list = A.tolist()
    B_list = B.tolist()
    
    A2 = matrix_multiply(A_list, A_list)
    A2_minus_B = matrix_subtract(A2, B_list)
    term1 = matrix_multiply(A_list, A2_minus_B)
    
    B_plus_A = matrix_add(B_list, A_list)
    B_plus_A_times_B = matrix_multiply(B_plus_A, B_list)
    term2 = scalar_multiply(2, B_plus_A_times_B)
    
    result = matrix_subtract(term1, term2)
    return np.array(result)

print("="*40)
print("ITERATIVE IMPLEMENTATION")
print("="*40)

start = time.time()
result_iter = matrix_expression_iterative(A, B)
time_iter = time.time() - start

print("\nResult:")
print(result_iter)
print(f"\nTime: {time_iter:.6f}s")

ITERATIVE IMPLEMENTATION

Result:
[[  -75.  -357.  -788.]
 [  -40.  -156.  -359.]
 [ -147.  -607. -1291.]]

Time: 0.000177s


### Comparison

In [43]:
import numpy as np
import time

print("\n" + "="*40)
print("COMPARISON")
print("="*40)

print(f"\nResults match: {np.allclose(result_numpy, result_iter)}")
print(f"\nNumPy time: {time_numpy:.6f}s")
print(f"Iterative time: {time_iter:.6f}s")
print(f"Speedup: {time_iter/time_numpy:.1f}x")


COMPARISON

Results match: True

NumPy time: 0.003694s
Iterative time: 0.000177s
Speedup: 0.0x
